#pragma once

#ifndef LE_INITIALIZATION_MACROS
#define LE_INITIALIZATION_MACROS
#endif

// LE_INIT_EXCLUSIVE_SDL
// LE_INIT_EXCLUSIVE_GLFW
// LE_INIT_EXCLUSIVE_OPENGL
// LE_INIT_EXCLUSIVE_VULKAN

#ifdef LE_INIT_EXCLUSIVE_SDL
#define LE_INTERNAL_INITMACRO_SDL 1
#elif defined(LE_INIT_EXCLUSIVE_GLFW)
#define LE_INTERNAL_INITMACRO_GLFW 1
#else
#define LE_INTERNAL_INITMACRO_SDL 1
#define LE_INTERNAL_INITMACRO_GLFW 1
#define LE_INTERNAL_INITMACRO_LIBINCLUSIVE 1
#endif

#ifdef LE_INIT_EXCLUSIVE_OPENGL
#define LE_INTERNAL_INITMACRO_OPENGL 1
#elif defined(LE_INIT_EXCLUSIVE_VULKAN)
#define GLFW_INIT_VULKAN 1
#define LE_INTERNAL_INITMACRO_VULKAN 1
#else
#define LE_INTERNAL_INITMACRO_OPENGL 1
#define GLFW_INIT_VULKAN 1
#define LE_INTERNAL_INITMACRO_VULKAN 1
#define LE_INTERNAL_INITMACRO_IMPLINCLUSIVE 1
#endif

